GRANT USAGE ON * . * TO 'ragemp'@'localhost' IDENTIFIED BY 'ragemp' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

CREATE DATABASE `ragemp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `ragemp` . * TO 'ragemp'@'localhost' WITH GRANT OPTION;
